src/main/java/entity/Order.java
package entity;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;
public class Order extends AbstractEntity<Long> {
    private static final long serialVersionUID = 3026083684140455633L;
    private Integer idAccount;
    private List<OrderItem> items;
    private Timestamp created;
    private boolean isUserWantToPayByCash;
    private String orderStatus;
    private String orderStatusMessage;

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getOrderStatusMessage() {
        return orderStatusMessage;
    }

    public void setOrderStatusMessage(String orderStatusMessage) {
        this.orderStatusMessage = orderStatusMessage;
    }

    public Order() {
    }

    public Integer getIdAccount() {
        return idAccount;
    }

    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
    }

    public boolean isUserWantToPayByCash() {
        return isUserWantToPayByCash;
    }

    public void setUserWantToPayByCash(boolean userWantToPayByCash) {
        isUserWantToPayByCash = userWantToPayByCash;
    }

    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public BigDecimal getTotalCost() {
        BigDecimal cost = BigDecimal.ZERO;
        if (items != null) {
            for (OrderItem item : items) {
                cost = cost.add(item.getProduct().getPrice().multiply(BigDecimal.valueOf(item.getCount())));
            }
        }
        return cost;
    }

    @Override
    public String toString() {
        return String.format("Order [id=%s, idAccount=%s, items=%s, created=%s]", getId(), idAccount, items, created);
    }
}

src/main/webapp/WEB-INF/JSP/fragment/aside.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="ishop" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="language" value="${pageContext.request.locale}"  scope="session"/>
<fmt:setLocale value="${language}" />
<fmt:setBundle basename="language" />
<div class="visible-xs-block xs-option-container">
	<a class="pull-right" data-toggle="collapse" href="#productCatalog">Product catalog <span class="caret"></span></a>
	<a data-toggle="collapse" href="#findProducts">Find products <span class="caret"></span></a>
</div>
<form class="search" action="/search">
	<div id="findProducts" class="panel panel-success collapse">
		<div class="panel-heading"><fmt:message key="label.findproducts" /></br></div>
		<div class="panel-body">
			<div class="input-group">
				<input type="text" name="query" class="form-control" placeholder="Search query" value="${searchForm.query }">
				<span class="input-group-btn">
					<a id="goSearch" class="btn btn-default"><fmt:message key="label.Go" /></br></a>
				</span>
			</div>
			<div class="more-options">
				<a data-toggle="collapse" href="#searchOptions"><fmt:message key="label.MoreFilters" /><span class="caret"></span></a>
			</div>
		</div>
		<div id="searchOptions" class="collapse">
			<ishop:category-filter categories="${CATEGORY_LIST }" />
			<ishop:producer-filter producers="${PRODUCER_LIST }" />
		</div>
	</div>
</form>
<div id="productCatalog" class="panel panel-success collapse">
	<div class="panel-heading"><fmt:message key="label.ProductCatalog" /></div>
	<div class="list-group">
		<c:forEach var="category" items="${CATEGORY_LIST }">
			<a href="/products${category.url }" class="list-group-item ${selectedCategoryUrl == category.url ? 'active' : '' }">
				<span class="badge">${category.productCount}</span> ${category.name}
			</a>
		</c:forEach>
		<form >
           <input type="number"  name="minprice" id="minprice" value="${sessionScope.minprice}"  required ><fmt:message key="label.MinPrice" /></input>
           <input type="number" name="maxprice" id="maxprice"  value="${sessionScope.maxprice}"  required><fmt:message key="label.MaxPrice" /></input>
           <input type="button"  id="submitSort" value =<fmt:message key="label.SubmitPriceRange" /> />
		</form>
		<input type="button" id="resetSort" value =<fmt:message key="label.ResetPriceRange"/> />
	</div>
	<form action="/productPerPageController" method="post"  id="productCountForm" style="margin-top:5px;float:left;">
                    <p >Products per Page</p>
                    <select  name ="productCount" id="productCount">
                     <option disabled>Products per page</option>
                      <option value="24">24</option>
                      <option value ="12">12</option>
                      <option value ="12">8</option>
                      <option value ="6">6</option>
                      <option value ="4">4</option>
                      <option value = "2">2</option>
                    </select>
                    <p><input type="submit" value = <fmt:message key="label.SaveValue" /> ></input</p>
                    </form>
</div>

src/main/webapp/WEB-INF/JSP/fragment/footer.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="tag-files" tagdir="/WEB-INF/tags"%>
<div class="container">
	<p class="text-center">
		IShop Webapp for Java PreProd2018
	</p>
</div>

src/main/webapp/WEB-INF/JSP/fragment/header.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="tag-files" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ishopNav" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/products">Take A Ride</a>
			<tag-files:locale/>
		</div>
		<div class="collapse navbar-collapse" id="ishopNav">
			<ul id="currentShoppingCart" class="nav navbar-nav navbar-right ${CURRENT_SHOPPING_CART == null ? ' hidden' : ''}">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-shopping-cart" aria-hidden="true"></i> Shopping cart (<span class="total-count">${CURRENT_SHOPPING_CART.totalCount}</span>)<span class="caret"></span>
					</a>
					<div class="dropdown-menu shopping-cart-desc">
						Total count: <span class="total-count">${CURRENT_SHOPPING_CART.totalCount} </span><br>
						Total cost: <span class="total-cost">${CURRENT_SHOPPING_CART.totalCost}</span><br>
						<a href="/shopping-cart" class="btn btn-primary btn-block">View cart</a>
					</div>
				</li>
			</ul>
			<tag-files:signIn/>
			<c:if test="${sessionScope.CURRENT_ACCOUNT != null}">
                 <a href="/my-orders" class="btn btn-primary navbar-btn navbar-right sign-in"><i  aria-hidden="true"></i>My orders</a>
            </c:if>
		</div>
	</div>
</nav>

src/main/webapp/WEB-INF/JSP/fragment/hiddenFiled.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<input name="captcha_code" value="${sessionScope.captcha_code}">

src/main/webapp/WEB-INF/JSP/fragment/my-orders-tbody.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" trimDirectiveWhitespaces="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<c:forEach var="order" items="${orders}">
      <tr class="item">
          <td><a href="/order?id=${order.id}">Order # ${order.id}</a></td>
          <td><fmt:formatDate value="${order.created }" pattern="yyyy-MM-dd HH:mm" /></td>
          <td>${order.orderStatus}</td>
          <td>${order.orderStatusMessage}</td>
          	</tr>
</c:forEach>

src/main/webapp/WEB-INF/JSP/fragment/product-list.jsp
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>
<%@ taglib prefix="ishop" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="language" value="${pageContext.request.locale}"  scope="session"/>
<fmt:setLocale value="${language}" />
<fmt:setBundle basename="language" />
<c:if test="${products.isEmpty() == true}">
  <h2>No products matches your request parameters</h2>
</c:if>
<c:forEach var="p" items="${products }">
	<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xlg-2">
		<div id="product${p.id }" class="panel panel-default product">
			<div class="panel-body">
				<div class="thumbnail">
					<img src="/${p.imageLink }" alt="${p.name }">
					<div class="desc">
						<div class="cell">
							<p>
								<span class="title">Details</span> ${p.description }
							</p>
						</div>
					</div>
				</div>
				<h4 class="name">${p.name }</h4>
				<div class="code">Code: ${p.id }</div>
				<div class="price">$ ${p.price } /per day</div>
				<a class="btn btn-primary pull-right buy-btn" data-id-product="${p.id }"><fmt:message key="label.buy" /></a>
				<div class="list-group">
					<span class="list-group-item"><small>Category:</small><span class="category">${p.category }</span></span>
					<span class="list-group-item"><small>Producer:</small><span class="producer">${p.producer }</span></span>
				</div>
			</div>
		</div>
	</div>
</c:forEach>